/**
 * script-word-count-property.test.js
 * Property-based tests for Script_Generator word count bounds (Property 6).
 *
 * **Validates: Requirements 8.2, 8.8**
 *
 * Property 6: Script Word Count Bounds
 * For any script generated by the Script_Generator, the word count of the
 * stored script SHALL be between 130 and 200 words (inclusive), where any
 * script exceeding 200 words is trimmed to the nearest sentence boundary
 * at or below 150 words.
 *
 * Feature: ai-video-automation-saas, Property 6: Script Word Count Bounds
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { countWords, enforceScriptWordLimit } from './script-generator.js';

// ---------------------------------------------------------------------------
// Word / script generators
// ---------------------------------------------------------------------------

/**
 * Build a script with exactly `wordCount` words.
 * Every 10th word ends with a sentence-terminating character (`.`) so that
 * the trimmer can always find a clean sentence boundary.
 *
 * @param {number} wordCount
 * @returns {string}
 */
function buildScript(wordCount) {
  const words = [];
  for (let i = 0; i < wordCount; i++) {
    // Every 10th word (1-indexed) is a sentence boundary
    words.push((i + 1) % 10 === 0 ? 'word.' : 'word');
  }
  return words.join(' ');
}

/**
 * Arbitrary: script with word count in [minWords, maxWords].
 * All generated scripts include sentence boundaries every 10 words.
 */
function arbScript(minWords, maxWords) {
  return fc
    .integer({ min: minWords, max: maxWords })
    .map((n) => buildScript(n));
}

// ---------------------------------------------------------------------------
// Property A — Scripts at or under 200 words pass through unchanged
// ---------------------------------------------------------------------------

describe('Property 6A — scripts ≤200 words are returned unchanged', () => {
  it('enforceScriptWordLimit returns the exact same string for scripts with 1–200 words', () => {
    /**
     * **Validates: Requirements 8.8**
     * For any script whose word count is already within the 200-word ceiling,
     * enforceScriptWordLimit() MUST return the script unmodified.
     */
    fc.assert(
      fc.property(arbScript(1, 200), (script) => {
        const result = enforceScriptWordLimit(script);
        return result === script;
      }),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property B — Scripts over 200 words are trimmed to ≤150 words
// ---------------------------------------------------------------------------

describe('Property 6B — scripts >200 words are trimmed to ≤150 words', () => {
  it('enforceScriptWordLimit trims any script with 201–300 words to at most 150 words', () => {
    /**
     * **Validates: Requirements 8.2, 8.8**
     * For any script whose word count exceeds the 200-word maximum,
     * enforceScriptWordLimit() MUST produce a result whose word count
     * is at most 150.
     */
    fc.assert(
      fc.property(arbScript(201, 300), (script) => {
        const result = enforceScriptWordLimit(script);
        return countWords(result) <= 150;
      }),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property C — Sentence boundary preserved on trim
// ---------------------------------------------------------------------------

describe('Property 6C — trimmed output ends at a sentence boundary', () => {
  it('enforceScriptWordLimit returns a result ending with . ! or ? for scripts over 200 words', () => {
    /**
     * **Validates: Requirements 8.8**
     * When a script with sentence boundaries every 10 words is trimmed,
     * the trimmed result must end with a sentence-terminating character.
     */
    fc.assert(
      fc.property(arbScript(201, 300), (script) => {
        const result = enforceScriptWordLimit(script);
        return /[.!?]$/.test(result.trim());
      }),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property D — Trimmed word count never drops to zero for non-empty input
// ---------------------------------------------------------------------------

describe('Property 6D — trimmed output is never empty for non-empty input with a sentence boundary', () => {
  it('enforceScriptWordLimit never returns an empty string for scripts with at least one sentence boundary', () => {
    /**
     * **Validates: Requirements 8.8**
     * As long as the input contains at least one sentence boundary and is
     * non-empty, enforceScriptWordLimit() MUST return a non-empty string.
     * Word count of the result must be ≥ 1.
     */
    fc.assert(
      fc.property(
        // Use a range spanning both below-limit and above-limit inputs
        arbScript(1, 300),
        (script) => {
          const result = enforceScriptWordLimit(script);
          return countWords(result) >= 1;
        },
      ),
      { numRuns: 300 },
    );
  });
});

// ---------------------------------------------------------------------------
// Concrete boundary tests
// ---------------------------------------------------------------------------

describe('Concrete boundary cases for enforceScriptWordLimit', () => {
  it('exactly 200 words → returned unchanged', () => {
    const script = buildScript(200);
    expect(countWords(script)).toBe(200);

    const result = enforceScriptWordLimit(script);

    expect(result).toBe(script);
    expect(countWords(result)).toBe(200);
  });

  it('exactly 201 words → trimmed to ≤150 words', () => {
    const script = buildScript(201);
    expect(countWords(script)).toBe(201);

    const result = enforceScriptWordLimit(script);

    expect(countWords(result)).toBeLessThanOrEqual(150);
    // Should end at a sentence boundary
    expect(result).toMatch(/[.!?]$/);
  });

  it('exactly 150 words → returned unchanged', () => {
    const script = buildScript(150);
    expect(countWords(script)).toBe(150);

    const result = enforceScriptWordLimit(script);

    expect(result).toBe(script);
    expect(countWords(result)).toBe(150);
  });
});
